#### [Communicating with Child Components](https://plnkr.co/edit/NPY5og89qxa1jhWuOHtw)
#### [Communicating with Parent Components](https://plnkr.co/edit/Rm0nL9uMgGPUO3j7EH0F)
#### [Using Template Variables To Interact With Child Components](https://plnkr.co/edit/iOJ6d1tsUra0qbNYX54P)
#### [Styling Components And Navigation Showing](https://plnkr.co/edit/zIOcnEtO4Hx4u59AqoGx?p=info)
#### [Repeating Data with ngFor](https://plnkr.co/edit/UoJWGBKmwsHuI4HvooIl)
#### [Handling Null Values with the Safe-Navigation Operator](https://plnkr.co/edit/K8JTinIjcw0u7FiuZpMM)
#### [Hiding and Showing Content with ngIf](https://plnkr.co/edit/LXnlULhj6nBPO7yifo7A)
#### [Hiding Content with the [Hidden] Binding](https://plnkr.co/edit/4Ui7kEHOp3fPLkcYaG6B)
#### [Hiding and Showing Content with ngSwitch](https://plnkr.co/edit/Vilb8799fzOC7pVsA5pR)
#### []
